### ISSUE TITLE
Perseuspy error in DP

### ISSUE THREAD

**Issue by fazeliniah** [jdrudolph/perseuspy#2]
Hi,
I have attached the error message that I got when I ran the DP in Perseus 1.6.0.7. I am not sure what the message means. Should I downgrade to Perseuspy 0.1.3?
Any help is greatly appreciated. 
H
[DP_error.pptx](https://github.com/jdrudolph/perseuspy/files/1372203/DP_error.pptx)

**Comment by jdrudolph** [comment]
The link to your file does not work for me. Can you describe what you did and what the error reads.
How did you create the rawFilesTable.txt?

**Comment by fazeliniah** [comment]
Hi 
Thanks for getting back to me. I think I fixed the issue. The problem was with my "rawfiletable.txt". After fixing that, it is now working just fine. 
H

**Comment by jdrudolph** [comment]
Perfect!
