### ISSUE TITLE
dP ratio mod/base not in list

### ISSUE THREAD

**Issue by animesh** [jdrudolph/perseuspy#3]
getting stuck with "dP ratio mod/base not in list" error  
![image](https://user-images.githubusercontent.com/21457/32334860-d8ccc7ee-bfeb-11e7-923f-c58d3dacc878.png), can see that the 55th column in "allPeptides.txt" is "DP Ratio mod/base", so could this error be just due to version as the error screenshot mentions?

**Comment by jdrudolph** [comment]
Its hard for me to reproduce this error without all the data... For now you can try to update to the latest version of `perseuspy` (via `pip`), and `PluginDependentPeptides` (via plugin store). Make sure the `allPeptides.txt` actually contains the `DP Ratio mod/base` column.

**Comment by animesh** [comment]
Thanks for the response @jdrudolph :+1: i did update the perseuspy version and can confirm that "allPeptides.txt actually contains the DP Ratio mod/base" (can share the file if the need be, just that it is huge...). To note now is that the error has changed in nature to something like "Parameter does not exist... "
![image](https://user-images.githubusercontent.com/21457/32417412-ae9b27de-c259-11e7-8c83-b42cec76549d.png) , any ideas? 

PS: using 1.6.0.2 version of plugins, however perseus is 1.6.0.7

**Comment by jdrudolph** [comment]
haven't seen this error before... maybe it's best to wait for the next Perseus version, where I can make sure that all parts are working for one specific version. The dependent peptides and underlying interop plugin are both currently undergoing lots of changes. For now, you can still access the DP information directly from the allPeptides table, albeit in a less convenient format.
